# Site settings
title: OH CHAE YOUNG
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: OH CHAE YOUNG
user_description: I'm a backend developer lived in South Korea. I like to imagine useful service and make it a reality. Also, I like to communicate with people through my work.
user_title: Backend Developer
email: web3765@gmail.com
twitter_username: lorem_ipsum
github_username:  wallace
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
